# Site settings
# You can update website by simply updating this config file!
title: Machine Learning 
TeacherEmail: peiyuanwu@ntu.edu.tw
description: "Pei-Yuan Wu"
location: 106 臺北市大安區羅斯福路四段 1 號博理館 530 室
phone: 02-3366-3700 ext.6530


url: https://ntueemlta2022.github.io
year: "2022 Fall"
TAemail: ntueemlta2022@gmail.com
TAs:
  - name: 林仲偉
    email: r10942198@ntu.edu.tw
  - name: 賴彥儒
    email: r09942079@ntu.edu.tw


# Syllabus
syllabus:
  - title: Week 01
    slides:
      - title: Syllabus
        kind: file-pdf-o
        path: ./slides/ML syllabus (109-1).pdf
      - title: Introduction
        kind: file-pdf-o
        path: ./slides/W1a_Introduction.pdf
      - title: Regression
        kind: file-pdf-o
        path: ./slides/W1b_Regression.pdf
      - title: W1-video
        kind: play-circle
        path: https://drive.google.com/drive/folders/1-iHwvCefqNQCySxwoohmYbpePZq7wqoR

  - title: Week 02
    slides:
      - title: Bias and Variance
        kind: file-pdf-o
        path: ./slides/W2a_Bias and Variance.pdf
      - title: Classification
        kind: file-pdf-o
        path: ./slides/W2b_Classification (v2).pdf
      - title: Logistic Regression
        kind: file-pdf-o
        path: ./slides/W2c_Logistic Regression (v4).pdf
      - title: W2-video
        kind: play-circle
        path: https://drive.google.com/drive/folders/1jGBuc7pZehO_9FMdTL1ahfTVIGp5aoj2?usp=sharing

  - title: Week 03
    slides:
      - title: Deep_Learning
        kind: file-pdf-o
        path: ./slides/W3a_DL_introduction.pdf
      - title: Gradient Descent
        kind: file-pdf-o
        path: ./slides/W3b_Gradient Descent.pdf
      - title: Backpropagation
        kind: file-pdf-o
        path: ./slides/W3c_BP (v2).pdf  
      - title: DNN
        kind: file-pdf-o
        path: ./slides/W3e_DNN tip.pdf
      - title: W3-video
        kind: play-circle
        path: https://drive.google.com/drive/folders/1telw5nIfU2zAojDErOETD2RF3lx7SirZ?usp=sharing
  
  - title: Week 04
    slides:
      - title: CNN
        kind: file-pdf-o
        path: ./slides/W4a_CNN.pdf
      - title: W4-video
        kind: play-circle
        path: https://www.youtube.com/watch?v=OP5HcXJg2Aw&list=PLJV_el3uVTsMhtt7_Y6sgTHGHp1Vb2P2J&index=10

  - title: Week 05
    slides:
      - title: PCA
        kind: file-pdf-o
        path: ./slides/W5a_PCA.pdf
      - title: W5-video
        kind: play-circle
        path: https://drive.google.com/drive/folders/1FCQjw6BMc-AjKwQJlYZp_mpPbPKyuNXC?usp=sharing
   
  - title: Week 06
    slides:
      - title: Auto Encoder
        kind: file-pdf-o
        path: ./slides/W6a_auto.pdf
      - title: TSNE
        kind: file-pdf-o
        path: ./slides/W6b_TSNE.pdf
      - title: W6-video
        kind: play-circle
        path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 07
    slides:
      - title: RNN
        kind: file-pdf-o
        path: ./slides/W7_RNN.pdf
      - title: TSNE
        kind: Gradient Boosting
        path: ./slides/W7_Gradient_boosting.pdf
      - title: W6-video
        kind: play-circle
        path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: More to go...
  
# Homework
# Please follow the format below to update the content.
homeworks:
  - title: HW1 - Regression
    links:
      - title: video # video
        kind: youtube-play 
        url: https://www.youtube.com/watch?v=Wcp4VAAM468
      - title: slide # slide
        kind: file-pdf-o 
        url: https://www.kaggle.com
      - title: kaggle # kaggle
        kind: tasks  
        url: https://www.kaggle.com
      - title: colab # colab
        kind: cloud 
        url: https://colab.research.google.com

  - title: To Be Discussed...

  # - title: HW2 - CNN
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com
 


# Resources:
resources:
  - title: 2021 fall 機器學習網站 - 吳沛遠
    url: https://ntueeml.github.io/ml-website/

  - title: 2022 spring 機器學習網站 - 李宏毅
    url: https://speech.ee.ntu.edu.tw/~hylee/ml/2022-spring.php

  - title: 李宏毅 Youtube
    url: https://www.youtube.com/c/HungyiLeeNTU

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
networks:
  - kind: facebook
    title: Join Discussion
    url: https://www.facebook.com/groups/412720760954309/?notif_id=1661958299977609&notif_t=groups_more_posts_in_new_group&ref=notif

################ website theme design ################
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3' # color for button
  special-links: '#FFCC00'

# Footer settings
footer: https://ntueemlta2022.github.io

# Build settings
markdown: kramdown
permalink: pretty