###### EDIT NOTE ######
# 1. You can update website by simply updating this config file!
# 2. Please follow the format to edit. (alignment, variable name, etc.)
#    > For slides: don't forget to upload pdf to ./slides/weekx !
# 3. For more detail, please contact author: R10942198@ntu.edu.tw

# Site settings
title: Machine Learning 
description: "Pei-Yuan Wu, Hung-Yi Lee"
location: 106 臺北市大安區羅斯福路四段 1 號博理館 530 室
phone: 02-3366-3700 ext.6530

url: https://ntueemlta2022.github.io
thumbnail: thumbnail.jpg
year: "2022 Fall"
TAemail: ntueemlta2022@gmail.com
TAs:
  - name: 林仲偉
    email: r10942198@ntu.edu.tw
  - name: 賴彥儒
    email: r09942079@ntu.edu.tw

TeacherEmail: peiyuanwu@ntu.edu.tw

# Syllabus
syllabus:
  - title: Week 01 (Moon Fest.)
    slides:
      # - title: Syllabus
      #   kind: file-pdf-o
      #   path: ./slides/week1/ML syllabus (109-1).pdf
      # - title: W1-video
      #   kind: play-circle
      #   path: https://drive.google.com/drive/folders/1-iHwvCefqNQCySxwoohmYbpePZq7wqoR

  - title: Week 02
    slides:
      - title: What is ML？
        kind: file-pdf-o
        path: ./slides/week2/W2_Introduction.pdf
      - title: Regression
        kind: file-pdf-o
        path: ./slides/week2/W2_Regression.pdf
      # - title: W2-video
      #   kind: play-circle
      #   path: https://drive.google.com/drive/folders/1-iHwvCefqNQCySxwoohmYbpePZq7wqoR

  - title: Week 03
    slides:
      - title: Bias and Variance
        kind: file-pdf-o
        path: ./slides/week3/W3a_Bias and Variance.pdf
      - title: Classification
        kind: file-pdf-o
        path: ./slides/week3/W3b_Classification (v2).pdf
      - title: Logistic Regression
        kind: file-pdf-o
        path: ./slides/week3/W3c_Logistic Regression (v4).pdf
      # - title: W3-video
      #   kind: play-circle
      #   path: https://drive.google.com/drive/folders/1jGBuc7pZehO_9FMdTL1ahfTVIGp5aoj2?usp=sharing

  - title: Week 04
    slides:
      - title: Deep Learning
        kind: file-pdf-o
        path: ./slides/week4/W4_DL_introduction.pdf
      - title: Gradient Descent
        kind: file-pdf-o
        path: ./slides/week4/W4_Gradient Descent.pdf
      - title: Backpropagation
        kind: file-pdf-o
        path: ./slides/week4/W4_BP (v2).pdf  
      - title: Tips for DL
        kind: file-pdf-o
        path: ./slides/week4/W4_DNN tip.pdf
      # - title: W4-video
      #   kind: play-circle
      #   path: https://drive.google.com/drive/folders/1telw5nIfU2zAojDErOETD2RF3lx7SirZ?usp=sharing
  
  - title: Week 05
    slides:
      - title: CNN
        kind: file-pdf-o
        path: ./slides/week5/W5_CNN.pdf
      - title: PCA
        kind: file-pdf-o
        path: ./slides/week5/W5_PCA.pdf
      # - title: W5-video
      #   kind: play-circle
      #   path: https://www.youtube.com/watch?v=OP5HcXJg2Aw&list=PLJV_el3uVTsMhtt7_Y6sgTHGHp1Vb2P2J&index=10

  - title: Week 06
    slides:
      - title: Auto Encoder
        kind: file-pdf-o
        path: ./slides/week6/W6_autoencoder.pdf
      - title: Neighbor Embedding
        kind: file-pdf-o
        path: ./slides/week6/W6_TSNE.pdf
      # - title: W6-video
      #   kind: play-circle
      #   path: https://drive.google.com/drive/folders/1FCQjw6BMc-AjKwQJlYZp_mpPbPKyuNXC?usp=sharing
   
  - title: Week 07 (Guest Lecture)
    slides:
      # - title: W7-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 08
    slides:
      - title: RNN
        kind: file-pdf-o
        path: ./slides/week8/W8_RNN.pdf
      - title: Ensemble    
        kind: file-pdf-o
        path: ./slides/week8/W8_ensemble.pdf
      - title: AdaBoost
        kind: Gradient Boosting
        path: ./slides/week8/W8_adaBoost.pdf
      # - title: W8-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 09
    slides:
      - title: GMM and EM 
        kind: file-pdf-o
        path: ./slides/week9/W9_GMM_EM.pdf
      # - title: W9-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29
    
  - title: Week 10
    slides:
      - title: Semi-Supervised Learning
        kind: file-pdf-o
        path: ./slides/week10/W10_semi.pdf
      # - title: W10-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 11
    slides:
      - title: VAE
        kind: file-pdf-o
        path: ./slides/week11/W11_VAE.pdf
      # - title: W11-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 12
    slides:
      - title: SVM intro
        kind: file-pdf-o
        path: ./slides/week12/W12_L1_svm_intro.pdf
      - title: SVM Optimization
        kind: file-pdf-o
        path: ./slides/week12/W12_L2_svm_optimization.pdf   
      # - title: W12-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29

  - title: Week 13
    slides:
      - title: SVM Kernel Method
        kind: file-pdf-o
        path: ./slides/week13/W13_L3_svm_kernel.pdf
      - title: Lagrange Duality
        kind: file-pdf-o
        path: ./slides/week13/W13_L4_duality_intro.pdf
      - title: Duality of SVM
        kind: file-pdf-o
        path: ./slides/week13/W13_L5_svm duality.pdf
      # - title: W6-video
      #   kind: play-circle
      #   path: https://youtube.com/playlist?list=PLxk9aIYXCa9czvYZSo1p3AlR9ydXyfJ29 
   
  - title: Week 14
    slides:
      
  - title: Week 15 (Guest Lecture)
    slides:
      
  - title: Week 16 (Final)
    slides:
 

# Resources:
resources:
  - title: 2022 spring 機器學習網站 - 李宏毅
    url: https://speech.ee.ntu.edu.tw/~hylee/ml/2022-spring.php

  - title: 2021 fall 機器學習網站 - 吳沛遠
    url: https://ntueeml.github.io/ml-website/

  - title: 李宏毅教授 Youtube
    url: https://www.youtube.com/c/HungyiLeeNTU


# Homework
# Please follow the format below to update the content.

homeworks:
  - title: HW1 - Regression
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com

  - title: HW2 - CNN
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com

  - title: HW3 - Embedding
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com  

  - title: HW4 - RNN
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com  

  - title: HW5 - SVM
  #   links:
  #     - title: video # video
  #       kind: youtube-play 
  #       url: https://www.youtube.com/watch?v=Wcp4VAAM468
  #     - title: slide # slide
  #       kind: file-pdf-o 
  #       url: https://www.kaggle.com
  #     - title: kaggle # kaggle
  #       kind: tasks  
  #       url: https://www.kaggle.com
  #     - title: colab # colab
  #       kind: cloud 
  #       url: https://colab.research.google.com  


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
networks:
  - kind: facebook
    title: Join Discussion
    url: https://www.facebook.com/groups/412720760954309/?notif_id=1661958299977609&notif_t=groups_more_posts_in_new_group&ref=notif


################ website theme design ################
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3' # color for button
  special-links: '#FFCC00'

# Footer settings
footer: https://ntueemlta2022.github.io

# Build settings
markdown: kramdown
permalink: pretty