# Site settings
title: Machine Learning 
TAemail: ntueemlta2022@gmail.com
url: https://ntueemlta2022.github.io
year: "2022 FALL "
description: "授課教授：吳沛遠"

homeworks:
  - number: HW1
    title: Regression
    video: https://www.youtube.com/watch?v=Wcp4VAAM468
    slide: https://www.kaggle.com
    kaggle: https://www.kaggle.com
    colab: https://colab.research.google.com

  - number: HW2
    title: CNN
    video: https://www.youtube.com/watch?v=Wcp4VAAM468
    slide: https://www.kaggle.com
    kaggle: https://www.kaggle.com
    colab: https://colab.research.google.com   

  - number: HW3
    title: Embedding
    video: 
    slide: 
    kaggle: 
    colab: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
networks:
  - kind: facebook
    title: Discussion Group
    url: https://www.facebook.com/groups/412720760954309/?notif_id=1661958299977609&notif_t=groups_more_posts_in_new_group&ref=notif

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Build settings
markdown: kramdown
permalink: pretty
