# Site settings
title: Machine Learning 
TAemail: ntueemlta2022@gmail.com
url: https://ntueemlta2022.github.io
year: "2022 FALL "
description: "授課教授：吳沛遠"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Facebook
    url: https://www.facebook.com/groups/412720760954309/?notif_id=1661958299977609&notif_t=groups_more_posts_in_new_group&ref=notif

# Build settings
markdown: kramdown
permalink: pretty
